services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      AUTO_SERVER_URL: 0
      SERVER_URL: https://stremioservice.kevinkochatt.com
    ports:
      - "8080:8080"
    volumes:
      - "./stremio-data:/root/.stremio-server"
    networks:
      - ondemand
    labels:
      caddy: stremio.kevinkochatt.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
networks:
  ondemand:
    external: true
